# Generated by Django 3.0.3 on 2020-05-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lof', '0002_auto_20200519_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='college_name',
            new_name='cardNumber',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='qq',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='schoolid',
            new_name='qqNumber',
        ),
        migrations.AddField(
            model_name='student',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='truename',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
