# Generated by Django 3.0.3 on 2020-05-25 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lof', '0004_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='isfound',
            new_name='status',
        ),
    ]
