# Generated by Django 3.0.3 on 2020-05-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lof', '0005_auto_20200525_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='iscard',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
