# Generated by Django 3.0.3 on 2020-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lof', '0006_event_iscard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='openid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
